#region File Description
//-----------------------------------------------------------------------------
// TypingWord.cs
// Matt McGrath
//-----------------------------------------------------------------------------
#endregion

#region Using Statements
using System.Collections.Generic;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Input;
using PixelEngine.Text;
#endregion

namespace AvatarTyping
{
     /// <summary>
     /// An abstract class which stores a static database of
     /// all the sentences the player will be typing.
     /// </summary>
     public abstract class SentenceDatabase
     {
          #region Static Word Database

          // Total Sentences: Only 1,515 according to debugger :(
          // Total Sentences: 1,515 (at 613'ish, 762)
          public static string[] Sentences = new string[]
          {
               #region Trial Mode Sentences. 5
               
               "Buy this game!",
               "Feed the poor",
               "Donate to the Poor Student Foundation",
               "Purchase!",
               "Buy this game or the kitten gets it",
               
               #endregion 
               
               #region Random (Unique).

               "Hello",
               "Goodbye",
               "Something witty",
               "Attack",
               "Long-winded sentence",
               "Slow movers",
               "Not very scary",
               "I need brains",
               "Brainnnn",
               "More witty writing",
               "I'll be there, eventually",
               "The typing. It hurts",
               "Did I put my face on today?",
               "My name is Stubbs",
               "So hungry",
               "You are on the menu",
               "Zebra", 
               "Pizza",
               "Guitar",
               "Soft Tissue", 
               "Boo",
               "Microsoft", 
               "Word",
               "Die",
               "Attack!",
               "Moan",
               "Redrum",
               "Murder",
               "Hungry",
               
               #endregion
               
               #region Single Words.  613
               
               // A. 40
               "Abortion pill",
               "Abstainer",
               "Abusive",
               "Accident-prone",
               "Accomplice",
               "Adenectomy",
               "Agnostic",
               "Agonize",
               "Affectationist",
               "Affirmative action",
               "Afraid",
               "Afro", 
               "Afternooner",
               "Aftershave",
               "Against all odds",
               "Ageist",
               "Albatross",
               "Alien",
               "Allergic",
               "Amateur",
               "Anchovy",
               "Android",
               "Angel",
               "Annoyance",
               "Antagonist",
               "Apotheosis",
               "Apple of discord",
               "Apple of my eye",
               "Antisperm",
               "Antiwomen",
               "Arouse",
               "Artsy",
               "Ashamed",
               "Assassin",
               "Atheist",
               "Audacious",
               "Automaton",
               "Avalanche",
               "Avoid",
               "Awkward",

               // B. 62
               "Babe",
               "Babysitter",
               "Baboonery",
               "Baby boomer",
               "Bachelor",
               "Back slapper",
               "Backwash",
               "Bacteria",
               "Bait and switch",
               "Baldness",
               "Bandit",
               "Bankrupt",
               "Barbarian",
               "Barfly",
               "Bear-hug",
               "Beatnik",
               "Beautiful",
               "Bed of roses",
               "Bed of nails",
               "Bed-wetter",
               "Befriend",
               "Befuddle",
               "Bellyache",
               "Benedict",
               "Besmirch",
               "Betray",
               "Big deal",
               "Bigfoot",
               "Binge eater",
               "Bizarre",
               "Blackout",
               "Blameworthy",
               "Blaspheme",
               "Blemish",
               "Blind date",
               "Blissful",
               "Blister",
               "Blood brother",
               "Bloodthirsty",
               "Bombastic",
               "Bombshell",
               "Booby trap",
               "Bookworm",
               "Boring",
               "Bossy",
               "Bothersome",
               "Bottom feeder",
               "Boxer",
               "Boy band",
               "Boyfriend",
               "Brain child",
               "Brain fart",
               "Brain freeze",
               "Brain power",
               "Brain-washer",
               "Brain-storm",
               "Brain-twister",
               "Buffoonery",
               "Buggery",
               "Bully",
               "Bureaucrat",
               "Butterfly effect",

               // C. 54
               "Caffeine addict",
               "Canker sore",
               "Captivate",
               "Cardboard box",
               "Carpal Tunnel Syndrome",
               "Carpetbagger",
               "Cataclysm",
               "Celibate",
               "Censor",
               "Cesspool",
               "Challenger",
               "Chameleon",
               "Champion",
               "Chaotic",
               "Character assassination",
               "Chauffeur",
               "Cheater",
               "Checkmate",
               "Chowderhead", 
               "Chubby",
               "Cinematheque",
               "Circus",
               "Civil disobedience",
               "Clairvoyant",
               "Clique",
               "Cloak-and-dagger",
               "Clone",
               "Clown",
               "Coddler",
               "Codependent",
               "Codpiece",
               "Cognitive dissonance",
               "Cognoscenti",
               "Comatose",
               "Combative",
               "Come-hither expression",
               "Comic relief",
               "Commando",
               "Concussion",
               "Condescend",
               "Conformist",
               "Conquer",
               "Conservative",
               "Cranky",
               "Creeper",
               "Crime against humanity",
               "Crooked",
               "Crusader",
               "Crush on you",          // More of an Idiom.
               "Cuckoo",
               "Cuddly",
               "Culprit",
               "Cupidinous",
               "Cybersquatter",

               // D. 50
               "Dainty",
               "Damage control",
               "Damsel",
               "Dangerous",
               "Daredevil",
               "Dateless",
               "Daydreamer",
               "Deadhead",
               "Death wish",
               "Debauchee",
               "Debonair",
               "Decoy",
               "Defeatism",
               "Defective",
               "Defining moment",
               "Defloration",
               "Defunct",
               "Degenerate",
               "Deleterious",
               "Delicate",
               "Delicious",
               "Demential",
               "Demigod",
               "Demonic",
               "Depressor",
               "Desirable",
               "Desperado",
               "Destroy",
               "Devastate",
               "Deviant",
               "Diabolical",
               "Diatribe",
               "Disaster",
               "Disgusting",
               "Disturbed",
               "Diversion",
               "Divide by zero",
               "Domestic violence",
               "Dominant",
               "Domino theory",
               "Doppelganger",
               "Double negative",
               "Down-and-out",
               "Dramatic irony",
               "Dreamy",
               "Dream team",
               "Drop-dead gorgeous",
               "Dulcinea",
               "Dwarf",
               "Dynamo",

               // E. 26
               "Early bird",
               "Earthbound",
               "Earwax",
               "Eavesdropper",
               "Ebullient",
               "Echolalia",
               "Educated",
               "Effeminate",
               "Effervescent",
               "Egomaniac",
               "Eloper",
               "Elusive",
               "Emaciation",
               "Emancipationist",
               "Emasculated",
               "Embarrassment",
               "Embellisher",
               "Entelechy",
               "Epitomize",
               "Erogenous zone",
               "Escape artist",
               "Evildoer",
               "Evil-minded",
               "Eviscerate",
               "Exchange student",
               "Exsanguinate",

               // F. 29
               "False memory syndrome",
               "Fast talker",
               "Fata Morgana",
               "Father figure", 
               "Fearsome",
               "Featherbrain",
               "Felon",
               "Feminist",
               "Fetal position",
               "Fetishist",
               "Fiendish laugh",
               "Fireproof",
               "Flabby",
               "Flamboyant",
               "Flying Dutchman",
               "Fodder",
               "Fondle",
               "Forlorn hope",
               "Fountain of Youth",
               "Feeble-minded",
               "Forbidden fruit",
               "Fratricide",
               "Fraudulent",
               "Frigid",
               "Frisky",
               "Frivolous",
               "Furious",
               "Futilitarian",
               "Fuzzy logic",

               // G. 25
               "Gabbler",
               "Gadabout",
               "Gallivant",
               "Gamer",
               "Gap-toothed",
               "Gender bender",
               "Gender gap",
               "Gentleman",
               "Gerrymander",
               "Ghost writer",
               "Global warming",
               "Glorifiable",
               "Glue sniffer",
               "Gluttonous",
               "Good-for-nothing",
               "Gold digger",
               "Golden ager",
               "Gormandize",
               "Goth",
               "Grave robber",
               "Great Divide",
               "Grumpy",
               "Guilt tripper",
               "Guerrilla theater",
               "Gutsy",

               // H. 24
               "Hacker",
               "Hail-fellow",
               "Hairball",
               "Half-witted",
               "Hallucination",
               "Halo Effect",
               "Hand puppet",
               "Hanky-panky",
               "Harlequin",
               "Hazardous",
               "Headbanger",
               "Headhunter",
               "Heartbroken",
               "Hedonist",
               "Heebie-jeebies",
               "Henotheist",
               "Hermaphrodite",
               "Hidden tax",
               "High-and-mighty",
               "Higgledypiggledy",
               "Hoodoo",
               "Horripilation",
               "Humorist",
               "Humpback",
               "Hungover",
               "Hypochondriac",

               // I. 20
               "Iconoclast",
               "Identical twin",
               "Identity crisis",
               "Identity thief",
               "Idiosyncrasy",
               "Idiot savant",
               "Illuminati",
               "Impedimenta",
               "Implode",
               "Imposter",
               "Incognito",
               "Incognita",
               "Indecent exposure",
               "Inferiority complex",
               "Infinite loop",
               "Infinite Monkey Theorem",
               "Inside job",
               "Ironclad",
               "Iron lung",
               "Ivy Leaguer",

               // J. 22
               "Jabberwocky",
               "Jackanapes",
               "Jack-in-the-box",
               "Jackpot",
               "Jailbait",
               "Jail break",
               "Jamboree",
               "Jane Doe",
               "Janitor",
               "Jawbreaker",
               "Jaywalker",
               "Jeremiad",
               "Jim-dandy",
               "Jock",
               "Jockstrap",
               "Jocosity",
               "Jinx",
               "Jubilarian",
               "Juggernaut",
               "Juvenile delinquent",
               "Juvenescent",
               "Juxtaposition",

               // K. 25  (Picked words I wouldn't normally use)
               "Kaleidoscope",
               "Kamikaze",
               "Kangaroo court",
               "Kaput",
               "Karma",
               "Keepsake",
               "Keyboardist",
               "Killed In Action",
               "Kiddo",
               "Kidney stone",
               "Killer",
               "Killer app",
               "Killjoy",
               "Kiltie",
               "Kiss me", // More of an idiom?
               "Kleptocrat",
               "Kleptomaniac",
               "Klutz",
               "Knave",
               "Knee-slapper",
               "Knockout",
               "Know-it-all",
               "Know-nothing",
               "Kook",
               "Kung fu",

               // L. 24
               "Lackadaisical",
               "Lackey",
               "Lactose-intolerant",
               "Lady-killer",
               "Lady Luck",
               "Lady of the evening",
               "Lallygag",
               "Languid",
               "Lap dance",
               "Last Judgment",
               "Libidinous",
               "Lisper",
               "Litterbug",
               "Loathsome",
               "Lobbyist",
               "Lobotomize",
               "Logic bomb",
               "Logophile",
               "Logorrhea",
               "Lonely-hearts",
               "Louche",
               "Love child",
               "Love handles",
               "Lovelorn",

               // M. 14
               "Machiavellian",
               "Maelstrom",
               "Mafioso",
               "Make-believe",
               "Malignant",
               "Meal ticket",
               "Medievalist",
               "Megalomaniac",
               "Meretricious",
               "Mirror image",
               "Miscegenation",
               "Misoneist",
               "Moneygrubber",
               "Muse",

               // N. 14
               "Nabob",
               "Nail-biter",
               "Naissance",
               "Naughty",
               "Nearsightedness",
               "Nefarious",
               "Negativistic",
               "Ninja",
               "Noble savage",
               "Nolo contendere",
               "Nonagenarian",
               "Nonpareil",
               "Nudist",
               "Nullipara",

               // O. 14
               "Obscurant",
               "Obsessive-compulsive",
               "Obsolescent",
               "Occupational hazard",
               "Oddball",
               "Odoriferous",
               "Off-the-wall",
               "Oneiromancer",
               "One-man band",
               "Osculation",
               "Ostentatious",
               "Overachiever",
               "Overactive imagination",
               "Overambitious",

               // P. 15
               "Pacification",
               "Page-turner",
               "Pandemonium",
               "Paradigmatic",
               "Peacemaker",
               "Pedant",
               "Pederast",
               "Peewee",
               "Penetrant",
               "Picaroon",
               "Pistol-whip",
               "Placebo effect",
               "Playboy",
               "Poetic justice",
               "Pyromaniac",

               // Q. 6
               "Quack",
               "Quagmire",
               "Quinquagenarian",
               "Quisling",
               "Quixotic",
               "QWERTY",

               // R. 18
               "Radiation sickness",
               "Rag doll",
               "Rambler",
               "Rampager",
               "Rancid",
               "Rapid-fire",
               "Rapscallion",
               "Rationalization",
               "Reactionary",
               "Reality check",
               "Recalcitrant",
               "Recluse",
               "Rejectee",
               "Right wing",
               "Ripple effect",
               "Rodeo clown",
               "Role-player",
               "Romancer",

               // S. 20
               "Saboteur",
               "Sad sack",
               "Safe sex",
               "Salt of the earth",
               "Scalawag",
               "Scandalmonger",
               "Scapegoat",
               "Scaredycat",
               "Scathing remark",
               "Scene-stealer",
               "Schadenfreude",
               "Schmoozer",
               "Schnorrer",
               "Security blanket",
               "Security risk",
               "Shenanigans",
               "Slaughterhouse",
               "Sleepwalker",
               "Sleepyhead", 
               "Squaller",

               // T. 25
               "Taboo",
               "Tabula rasa",
               "Tactician",
               "Tagalong",
               "Taleteller",
               "Tearjerker",
               "Technobabble",
               "Technophobia",
               "Teddy bear",
               "Teenybopper",    
               "Telemarketer",           
               "Theater of the absurd",
               "Theory of Everything",
               "Thespian",
               "Thingamajig",  
               "Time bomb",
               "Tingling sensation",
               "Toilet trainer",
               "Tongue twister",
               "Tooth fairy",
               "Top-heavy",
               "Trophy wife",
               "Truthiness",
               "Twilight zone",
               "Typhoid Mary",

               // U. 30
               "Ubiquitous",
               "Ugsome",
               "Ulcerative",
               "Umbilical cord",
               "Umbrageous",
               "Unabashed",
               "Unbearable",
               "Unbeatable",
               "Unbuttoned",
               "Uncalled-for",
               "Uncared-for",
               "Undead",
               "Underachiever",
               "Underdog",
               "Undernourished",
               "Undersexed",
               "Under-the-table",
               "Undesirable",
               "Undress",
               "Undying love", // More of an idiom.
               "Unemployable",
               "Unisexual",
               "Unzip me", // More of an idiom.
               "Upholster",
               "Upside down",
               "Upstage",
               "Uptight",
               "Urban legend",
               "Useless",
               "Uxoricide",

               // V. 29
               "Vacillate",
               "Vagabond",
               "Vaginismus",
               "Vagrant",
               "Vainglorious",
               "Valentine",
               "Vamp",
               "Vampire",
               "Vapid",
               "Vaporize",
               "Vegetable",
               "Vegetarian",
               "Vehement",
               "Vendettist",
               "Vengeance",
               "Verbal abuse", // More of an idiom?
               "Verisimilar",
               "Victimless crime",
               "Vigilante",
               "Vile",
               "Villain",
               "Vincible",
               "Violator",
               "Virgin",
               "Vixen",
               "Voiceless",
               "Voluptuous",
               "Vulgarian",
               "Vulnerable",

               // W. 20
               "Wacko",
               "Waddle",
               "Waggery",
               "Walkie-talkie",
               "Wallydrag", 
               "Wandering Jew",
               "Wangle",
               "Wattle",
               "Weekender",
               "Weeping willow",
               "Wet dream",
               "Wheezy",
               "Whippersnapper",
               "Whipping boy",
               "Whispering campaign",
               "White knight",
               "Whiz kid",
               "Winner's circle",
               "Womanizer",
               "Wordmonger",

               // X. 2
               "Xenophile",
               "Xenophobe",

               // Y. 9
               "Yahoo", 
               "Yammerer",
               "Yapper",
               "Yeasayer",
               "Yeast infection",
               "Yeti",
               "Yin and yang",
               "Yoo-hoo",
               "Yummy",

               // Z. 10
               "Zany",
               "Zealot",
               "Zenana",
               "Zephyr",
               "Zero hour",
               "Zeugma",
               "Zilch",
               "Zombify",
               "Zoonosis",
               "Zoophobia",
          
               #endregion
               
               #region Symptoms 75
               
               "Agitation",
               "Anxiety",
               "Apathy",
               "Bald spots",
               "Blackouts",
               "Bleeding",
               "Coma",
               "Compulsive behavior",
               "Confusion",
               "Craving alcohol",
               "Delusions",
               "Difficulty concentrating",
               "Difficulty falling asleep",
               "Difficulty finding words",
               "Difficulty learning new things",
               "Difficulty sleeping",
               "Difficulty solving problems",
               "Difficulty staying awake",
               "Disorientation",
               "Dizziness",
               //"Drainage or pus",
               "Drowsiness",
               "Early morning waking",
               "Easily distracted",
               "Emotional detachment",
               "Fainting",
               "Fear of air",
               "Fear of gaining weight",
               "Fear of water",
               "Detached from reality",
               "Feeling smothered",
               "Fever",
               "Fits of rage",
               "Flashbacks",
               "Forgetfulness",
               "Frightening dreams",
               "Frightening thoughts",
               "Hair loss",
               "Hallucinations",
               "Headache",
               "Hearing voices",
               "Impaired color vision",
               "Impaired judgment",
               "Impaired social skills",
               "Impulsive behavior",
               "Inappropriate behavior",
               "Burning sensation",
               "Lack of emotion",
               "Lack of motivation",
               "Lack of pleasure",
               "Lightheadedness",
               "Loss of consciousness",
               //"Lump or bulge",
               "Memory problems",
               "Mood swings",
               //"Multiple bruises of different ages",
               "Numbness or tingling",
               "Paranoid behavior",
               "Personality changes",
               "Poor concentration",
               "Pulling out hair",
               "Punching or kicking in sleep",
               "Repeats phrases",
               "Repetitive behaviors",
               "Restless",
               "Sadness",
               "Seizures",
               "Sense of impending doom",
               "Sleep walking",
               "Slow thinking",
               "Spinning sensation",
               "Swelling",
               "Tender to the touch",
               "Unusual behavior",
               "Visible deformity",
               "Warm to the touch",

               #endregion

               #region Game parodies. 3

               "Gears of Bore",
               "Call of Doody",
               "Modern Borefare", 
               
               #endregion
               
               // Not Used.
               #region Video Game Titles. 120+
               /*
               // Action Games. 62
               "Army of Two",
               "Battlefield",
               "BioShock",
               "Borderlands",
               "Braid",
               "Brothers in Arms",
               "Brutal Legend",
               "Call of Duty",
               "Castle Crashers",
               "Crackdown",
               "Dante's Inferno",
               "Dark Sector",
               "Darkest of Days",
               "The Darkness",
               "Dead or Alive",
               "Dead Space",
               "Devil May Cry",
               "Doom",
               "Duke Nukem",
               "Dynasty Warriors",
               "Eat Lead",
               "F.E.A.R",
               "Far Cry",
               "Frontlines: Fuel of War",
               "Gears of War",
               "Halo",
               "Haze",
               "Kane & Lynch",
               "Left 4 Dead",
               "Lost Planet",
               "Max Payne",
               "Medal of Honor",
               "Mirror's Edge",
               "Mortal Kombat",
               "Naughty Bear",
               "The Orange Box",
               "Perfect Dark",
               "Perfect Dark Zero",
               "Portal",
               "Prey",
               "Prince of Persia",
               "Quake",
               "Red Faction",
               "Rocket Knight",
               "Rumble Roses",
               "Serious Sam",
               "Shadow Complex",
               "Shadowrun",
               "Small Arms",
               "Soldier of Fortune",
               "Soul Calibur",
               "Splosion Man",
               "Stranglehold",
               "Street Fighter",
               "Tekken",
               "Time Shift",
               "TimeSplitters",
               "Turok",
               "Unreal Tournament",
               "Virtua Fighter",
               "Wet",
               "Wolfenstein",

               // Action Adventure. 20
               "Alan Wake",
               "Alone in the Dark",
               "Assassin's Creed",
               "Bully",
               "Castlevania",
               "Condemned",
               "Dead Rising",
               "Grand Theft Auto",
               "GUN",
               "Hitman",
               "Just Cause",
               "Kameo",
               "Ninja Gaiden",
               "Overlord",
               "Prototype",
               "Resident Evil",
               "Saint's Row",
               "The Sabotuer",
               "Silent Hill",
               "Too Human",

               // Role-Playing Games. 16
               "Blue Dragon",
               "Dragon Age",
               "Enchanted Arms",
               "Eternal Sonata",
               "Fable",
               "Fallout",
               "Final Fantasy",
               "Lost Odyssey",
               "Magna Carta",
               "Mass Effect",
               "Phantasy Star",
               "Resonance of Fate",
               "Star Ocean",
               "Tales of Vesperia",
               "The Elder Scrolls IV: Oblivion",
               "Two Worlds",

               // Sports. 10
               "Madden",
               "FIFA Soccer",
               "Fight Night",
               "NBA Live",
               "Pro Evolution Soccer",
               "Skate",
               "Tiger Woods PGA Tour",
               "Tony Hawk's Pro Skater",
               "Top Spin",
               "Virtua Tennis",

               // Rhythm Games. 8
               "Band Hero",
               "Dance Dance Revolution",
               "DJ Hero",
               "Guitar Hero",
               "Karaoke Revolution",
               "Lips",
               "Rock Band",
               "Rock Revolution",

               // Virtual Life Games. 2
               "The Sims",
               "Viva Pinata",
               */
               #endregion
               
               #region Video game quotes. 35

               "A man chooses, a slave obeys",
               "A winner is you!",
               "Ah! My leiben",
               "All I want is world peace, or a piece of the world",
               "All your base are belong to us",
               "Angels don't wait for slowpokes",
               "Do a barrel roll!",
               "I am error",
               "I feel asleep",
               "I need a weapon",
               //"I should have been the one to fill your dark soul with light!",
               "I won't hurt you, I just want to see what's inside",
               "I'm looking for sailors",
               //"I'm the grim reaper, Lardass, and you're my next customer",
               "Time to kick ass and chew bubble gum",//...and I'm all out of gum",
               "I've covered wars, you know",
               "Jill, here's a lockpick",
               "Let's get sweaty",
               "Our princess is in another castle",
               "Pills here!",
               "Say, \"Fuzzy pickles.\"",
               //"Shine Get!",
               "Stop right there criminal scum!",
               "The cake is a lie",
               "There was a hole here. It's gone now.",
               "You have died of dysentery",
               "You were almost a Jill sandwich!",
               "You spoony bard!",
               "You're an inspiration for birth control",
               "Your face, your ass. What's the difference?", 
               "We're goin' deep, and we're going hard!",
               "What are you waiting for? Christmas?",
               "What is a man? A miserable little pile of secrets.",
               "Would you kindly?",
               //"Ce m'est, Mario!",
               
               #endregion
               
               #region TV. 3
               
               //"Wacky Waving Inflatable Arm Flailing Tube Men",
               //"Wakka wakka, who wants to hear a funny-ass joke?",
               "Master of my domain",
               
               #endregion
               
               #region Popular Quotes. 7

               //"Born again?! No, I'm not. Excuse me for getting it right the first time.",
               "A Chuck Norris love scene is one where he lets the other guy live",
               "Anyone who says he can see through women is missing a lot",
               //"Curiosity killed the cat, but for a while I was a suspect",
               "You would make a lovely corpse",
               //"I haven't spoken to my wife in years. I didn't want to interrupt her.",
               "My fake plants died",// because I did not pretend to water them",
               
               #endregion
               
               #region Idioms: 762

               // A: 34
               "A fresh pair of eyes",
               "A little birdie told me",
               "A penny for your thoughts",
               "A picture is worth a thousand words",
               "A rolling stone gathers no moss",
               "Absence makes the heart grow fonder",
               "Accident waiting to happen",
               "Achilles' heel",
               "Act of God",
               "Actions speak louder than words",
               "Adam's apple",
               "Add insult to injury",
               "Against the grain",
               "Ahead of the curve",
               "Alive and kicking",
               "All bark and no bite",
               "All eyes on me",
               "All in your head",
               "All that glitters is not gold",
               "All's fair in love and war",
               "All's well that ends well",
               "Alter ego",
               "Always the bride's maid",
               "Ambulance chaser",
               "Ants in your pants",
               "Any Tom, Dick, or Harry",
               "Apples and oranges",
               "As cold as ice",
               "As mad as a hatter",
               "Asleep at the wheel",
               "At a snail's pace",
               "At death's door",
               "Average Joe",
               "Away with the fairies",

               // B: 86
               "Baby boomer",
               "Back-handed compliment",
               "Back to square one",
               "Back to the drawing board",
               "Backseat driver",
               "Bad apple",
               "Bad hair day",
               "Bad taste in your mouth",
               "Bag of bones",
               "Baker's dozen",
               "Ball is in your court",
               "Balls to the walls",
               "Banana republic",
               "Bandit territory",
               "Baptism of fire",
               "Bar fly",
               "Bare your heart",
               "Barking up the wrong tree",
               "Barrel of laughs",
               "Basket case",
               "Bat an eyelid",
               "Battle of nerves",
               "Be careful what you wish for",
               "Beam me up, Scotty",
               "Bean counter",
               "Bear the brunt",
               "Beat your brains out",
               "Beating a dead horse",
               "Beauty is only skin deep",
               "Bedroom eyes",
               "Bee in your bonnet",
               "Bee's Knees",
               "Been there, done that",
               "Beggars can't be choosers",
               "Behind bars",
               "Behind closed doors",
               "Behind the times",
               "Bell the cat",
               "Below par",
               "Below the belt",
               "Bend over backwards",
               "Beside myself",
               "Best of a bad bunch",
               "Best of both worlds",
               "Best thing since sliced bread",
               "Better half",
               "Better safe than sorry",
               "Between a rock and a hard place",
               "Beyond a shadow of a doubt",
               "Big fish in a small pond",
               "Big hitter",
               "Bigger fish to fry",
               "Bird-brain",
               "Birds and the bees",
               "Birthday suit",
               "Bite the bullet",
               "Bitter end",
               "Bitter pill to swallow",
               "Black and white",
               "Black sheep",
               "Blackballer",
               "Bleeding heart liberal",
               "Blessing in disguise",
               "Blind acceptance",
               "Blind as a bat",
               "Blind leading the blind",
               "Blood, sweat, and tears",
               "Blow a gasket",
               "Blew your mind",
               "Boldfaced liar",
               "Bone to pick",
               "Bouncing off the walls",
               "Bread and butter",
               "Break the ice",
               "Break your heart",
               "Breathe down your neck",
               "Bright-eyed and bushy-tailed",
               "Bring a knife to a gunfight",
               "Broken record",
               "Bull in a China shop",
               "Bun in the oven",
               "Bursting at the seams",
               "Bust my chops",
               "Busy as a bee",
               "Butterfingers",
               "Butterflies in your stomach",

               // C: 44
               "Call the dogs off",
               "Calm before the storm",
               "Can of worms",
               "Can't hack it",
               "Card up my sleeve",
               "Cash cow",
               "Cast a long shadow",
               "Cat burglar",
               "Cat got your tongue?",
               "Cat nap",
               "Catch-22",
               "Change of heart",
               "Chaps my ass",
               "Cheating death",
               "Cherry picker",
               "Chew the fat",
               "Child's play",
               "Class act",
               "Clean as a whistle",
               "Clean bill of health",
               "Cliffhanger",
               "Close but no cigar",
               "Close shave",
               "Cloud of suspicion",
               "Cloud nine",
               "Cock of the walk",
               "Cold day in hell",
               "Cold feet",
               "Cold shoulder",
               "Collateral damage",
               "Comfort zone",
               "Connect the dots",
               "Cool as a cat",
               "Couch potato",
               "Creme de la creme",
               "Crocodile tears",
               "Crunch time",
               "Cry-baby",
               "Cry wolf",
               "Curiosity killed the cat",
               "Cut a long story short",
               "Cut and run",
               "Cut to the chase",
               "Cutting edge",

               // D: 28
               "Dancing on your grave",
               "Dark horse",
               "Davey Jones' locker",
               "Dead as a dodo",
               "Dead man walking",
               "Dear John letter",
               "Death by a thousand cuts",
               "Deep pockets",
               "Deer in the headlights",
               "Devil's advocate",
               "Diamond in the rough",
               "Dime a dozen",
               "Dodge the bullet",
               "Dog and pony show",
               "Don't mention the war",
               "Don't shoot the messenger",
               "Double whammy",
               "Doubting Thomas",
               "Down and out",
               "Down for the count",
               "Down-to-earth",
               "Down the hatch",
               "Drawing a blank",
               "Dressed to kill",
               "Drop like flies",
               "Drop the ball",
               "Drown your sorrows",
               "Dumb as a rock",

               // E: 14
               "Eager beaver",
               "Eagle eyes",
               "Early bird catches the worm",
               "Easy as pie",
               "Easy peasy",
               "Eat like a pig",
               "Eat your heart out",
               "Egg on your face",
               "Elephant in the room",
               "Eleventh hour",
               //"Even a blind squirrel finds a nut once in a while",
               "Every man has his price",
               "Eye candy",
               "Eye for an eye",

               // F: 24
               "Face only a mother could love",
               "Face the music",
               "Face your demons",
               "Faint-hearted",
               "Fairweather friend",
               "Fall from grace",
               "Fall off the wagon",
               "Familiarity breeds contempt",
               "Famous last words",
               "Fat cat",
               "Fate worse than death",
               "Feast today, famine tomorrow",
               "Fifth wheel",
               "Figment of your imagination",
               "First come, first served",
               "Fishy",
               "Five o'clock shadow",
               "Flat as a pancake",
               "Foaming at the mouth",
               "Food for thought",
               "Foregone conclusion",
               "Fresh from the oven",
               "Freudian Slip",
               "Full of hot air",

               // G: 31
               "Get a grip",
               "Get away with murder",
               "Get the ball rolling",
               "Get your hands dirty",
               "Ghost of a chance",
               "Gift of the gab",
               "Give me a hand",
               "Glass ceiling",
               "Gloves are off",
               "Go bananas",
               "Go down swinging",
               "Go Dutch",
               "Go fly a kite",
               "Go for broke",
               "Go nuts",
               "Go play in traffic",
               "Go tell it to birds",
               "Go with the flow",
               "Go-to Guy",
               "Golden touch",
               "Gone fishing",
               "Good as gold",
               "Goody two-shoes",
               "Grain of salt",
               "Graveyard shift",
               "Greek to me",
               "Green-eyed monster",
               "Grinds my gears",
               "Guinea-pig",
               "Gunboat diplomacy",
               "Gung ho",

               // H: 26
               "Half-baked",
               "Handle with kid gloves",
               "Hanging by a thread",
               "Happy-go-lucky",
               "Hard as nails",
               "Hat trick",
               "Hatchet job",
               "Hay is for horses",
               "Head for the hills",
               "Head in the clouds",
               "Head over heels",
               "Heads will roll",
               "Heavy-handed",
               "Here today, gone tomorrow",
               "High as a kite",
               "Highway robbery",
               "Hit a nerve",
               "Hit and miss",
               "Hit the books",
               "Holier-than-thou",
               "Honor among thieves",
               "Horses for courses",
               "Hostile takeover",
               "Hot to trot",
               "House of cards",
               "Hunky Dory",

               // I: 21
               "Icing on the cake",
               "Ill-gotten gains",
               "In a heartbeat",
               "In a nutshell",
               "In a pickle",
               "In a tight spot",
               "In cahoots",
               "In cold blood",
               "In droves",
               "In full swing",
               "In like Flynn",
               "In spades",
               "In stitches",
               "In the bag",
               "In the flesh",
               "In the red",
               "In your face",
               "Indian summer",
               "Into thin air",
               "Iron fist",
               "Ivory tower",

               // J: 13
               "Jack-of-all-trades",
               "Jane Doe",
               "Jet setter",
               "Jog my memory",
               "John Doe",
               "John Hancock",
               "John Q Public",
               "Johnny-come-lately",
               "Joined at the hip",
               "Jump the gun",
               "Jump the shark",
               "Jump through hoops",
               "Just what the doctor ordered",

               // K: 14
               "Keeping you at arm's length",
               "Keep your fingers crossed",
               "Keep your pants on",
               "Kick the bucket",
               "Kill two birds with one stone",
               "Kindred spirit",
               "King of the castle",
               "Kiss and tell",
               "Kiss of death",
               "Kissing cousin",
               "Knight in shining armor",
               "Knock it off",
               "Knock on wood",
               "Knock your socks off",

               // L: 40
               "Labor of love",
               "Lame duck",
               "Landslide victory",
               "Lap dog",
               "Lap of the gods",
               "Larger than life",
               "Last gasp",
               "Last hurrah",
               "Last straw",
               "Last-ditch effort",
               "Laugh a minute",
               "Laughing stock",
               "Lay down the law",
               "Lean and mean",
               "Learn the ropes",
               "Lend an ear",
               "Lesser of two evils",
               "Let sleeping dogs lie",
               "Let your hair down",
               "Lie like a rug",
               "Life and limb",
               "Lightning rod",
               "Like a bat out of hell",
               "Like a beached whale",
               "Like a hawk",
               "Like a moth to a flame",
               "Like Chinese arithmetic",
               "Like clockwork",
               "Lily-livered",
               "Lion's share",
               "Lip service",
               "Loan shark",
               "Lock horns",
               "Lone wolf",
               "Long shot",
               "Loose cannon",
               "Lost your lunch",
               "Lost your marbles",
               "Lower your sights",
               "Luck of the draw",

               // M: 27
               "Made of money",
               "Make a killing",
               "Make a mountain out of a molehill",
               "Make my day",
               "Make out like a bandit",
               "Make waves",
               "Makes my blood boil",
               "Man proposes, God disposes",
               "Man's man",
               "Marked man",
               "Meet your Maker",
               "Megaphone diplomacy",
               "Mexican standoff",
               "Midas touch",
               "Mind your P's and Q's",
               "Misery guts",
               "Money doesn't grow on trees",
               "Money talks",
               "Monkey business",
               "Monkey see, monkey do",
               "Moot point",
               "Moral high ground",
               "More holes than Swiss cheese",
               "More than one way to skin a cat",
               "Much ado about nothing",
               "Mud-slinger",
               "My way or the highway",

               // N: 16
               "Nail in the coffin",
               "Nail-biter",
               "Nature of the beast",
               "Need no introduction",
               "Nerves of steel",
               "Nervous Nellie",
               "New kid on the block",
               "Night owl",
               "Ninth circle of hell",
               "No laughing matter",
               "Not my cup of tea",
               "Not on my watch",
               "Nothing to write home about",
               "Null and void",
               "Number cruncher",
               "Nutty as a fruitcake",

               // O: 26
               "Off the chart",
               "Off the grid",
               "Off your rocker",
               "Old wive's tale",
               "Olive branch",
               "On a roll",
               "On all fours",
               "On pins and needles",
               "On the dot",
               "On the lam",
               "On the level",
               "On the run",
               "On the wagon",
               "Once bitten, twice shy",
               "Once in a blue moon",
               "One hand washes the other",
               "One-man band",
               "Out of your league",
               "Out of the blue",
               "Out of this world",
               "Out on a limb",
               "Out to lunch",
               "Over my dead body",
               "Over the counter",
               "Over the hill",
               "Over the moon",

               // P: 37
               "Pain in the neck",
               "Paint the town red",
               "Pandora's box",
               "Pardon my French",
               "Pass the buck",
               "Pay the piper",
               "Peanut gallery",
               "Peeping Tom",
               "Penny pincher",
               "Pet peeve",
               "Photo finish",
               "Picture perfect",
               "Pink slip",
               "Plain Jane",
               "Plastic smile",
               "Play for keeps",
               "Play hard to get",
               "Play possum",
               "Play the field",
               "Play the fool",
               "Play with fire",
               "Poetry in motion",
               "Point the finger",
               "Poison pill",
               "Poker face",
               "Polish the apples",
               "Politically correct",
               "Pound of flesh",
               "Preaching to the choir",
               "Press the flesh",
               "Prince Charming",
               "Punching bag",
               "Puppy love",
               "Push the envelope",
               "Pushing up daisies",
               "Put lipstick on a pig",
               "Put the kybosh on it",

               // Q: 3
               "Quick on the trigger",
               "Quiet as a mouse",
               "Quitters never win",

               // R: 54
               "Rags to riches",
               "Rain on your parade",
               "Raining cats and dogs",
               "Rainy day",
               "Raise eyebrows",
               "Rat race",
               "Rather you than me",
               "Raw deal",
               "Read between the lines",
               "Real deal",
               "Recharge your batteries",
               "Recipe for disaster",
               "Red carpet",
               "Red herring",
               "Red letter day",
               "Red light district",
               "Red mist",
               "Red tape",
               "Reduce to ashes",
               "Reinvent the wheel",
               "Renaissance man",
               "Rest on your laurels",
               "Revenge is sweet",
               "Rewrite history",
               "Rhyme or reason",
               "Ride shotgun",
               "Ride with the tide",
               "Right as rain",
               "Right up your alley",
               "Ring a bell",
               "Rise and shine",
               "Rise from the ashes",
               "Rock the boat",
               "Rocket science",
               "Roll with the punches",
               "Roll your eyes",
               "Rolling in money",
               "Rome was not built in a day",
               "Rose-tinted glasses",
               "Rough and ready",
               "Rough around the edges",
               "Round the bend",
               "Rub shoulders",
               "Rub me the wrong way",
               "Rue the day",
               "Ruffle a few feathers",
               "Rule of thumb",
               "Run amok",
               "Run before you can walk",
               "Running circles around you",
               "Run-of-the-mill",
               "Running on empty",
               "Runs in the family",
               "Russian roulette",
               "Rusty needle",

               // S: 133
               "Sacred cow",
               "Safe and sound",
               "Safe bet",
               "Safety in numbers",
               "Sail close to the wind",
               "Salt in a wound",
               "Salt of the earth",
               "Same old, same old",
               "Save face",
               "Save your skin",
               "Saved by the bell",
               "Saving grace",
               "Say uncle",
               "Scared the daylights out of me",
               "Scarlet woman",
               "Scot free",
               "Scraping the barrel",
               "Screw loose",
               "Seamy side",
               "See eye to eye",
               "See red",
               "See the light",
               "Seed money",
               "Seeing is believing",
               "Seen better days",
               "Sold me down the river",
               "Sell like hotcakes",
               "Sell your soul",
               "Send you packing",
               "Serve time",
               "Serve your country",
               "Set in stone",
               "Set the wheels in motion",
               "Seventh heaven",
               "Shades of meaning",
               "Shaggy dog story",
               "Shake a leg",
               "Shape up or ship out",
               "Sharp as a tack",
               "Sharp cookie",
               "Sharpen your pencil",
               "Shed light",
               "Shifting sands",
               "Shot down in flames",
               "Shoot from the hip",
               "Shoot the breeze",
               "Shot your wad",
               "Shoot yourself in the foot",
               "Shooting fish in a barrel",
               "Short end of the stick",
               "Short-change",
               "Shot in the dark",
               "Shotgun wedding",
               "Show me the money",
               "Show me the ropes",
               "Show your true colors",
               "Shrinking violet",
               "Sick and tired",
               "Sight for sore eyes",
               "Sight to behold",
               "Signed, sealed and delivered",
               "Silence is golden",
               "Silver bullet",
               "Sing for your supper",
               "Sing like a canary",
               "Sink or swim",
               "Sit on the fence",
               "Sitting pretty",
               "Sitting duck",
               "Six feet under",
               "Skating on thin ice",
               "Skeleton in the closet",
               "Skin and bones",
               "Skin you alive",
               "Slap on the wrist",
               "Sleep like a baby",
               "Sleight of hand",
               "Slim chance",
               "Slip of the tongue",
               "Slipped through my fingers",
               "Slippery slope",
               "Slough of despond",
               "Slow and steady wins the race",
               "Slow boat to China",
               "Sly as a fox",
               "Smack in the face",
               "Small potatoes",
               "Smart as a whip",
               "Smell a rat",
               "Smoke and mirrors",
               "Smoke the peace pipe",
               "Smoking gun",
               "Smooth sailing",
               "Snake in the grass",
               "Snake oil",
               "Snug as a bug in a rug",
               "Something nasty in the woodshed",
               "Sour grapes",
               "Sow the seeds",
               "Speak of the devil",
               "Speaks volumes",
               "Spice of life",
               "Spill the beans",
               "Spin a yarn",
               "Spirit is willing, but the flesh is weak",
               "Spitting blood",
               "Spitting image",
               "Split hairs",
               "Spur of the moment",
               "Squeaky clean",
               "Start from scratch",
               "State of the art",
               "Status quo",
               "Stole your thunder",
               "Stew in your own juices",
               "Sticky fingers",
               "Still waters run deep",
               "Stitch in time saves nine",
               "Stool pigeon",
               "Strain every nerve",
               "Straw man argument",
               "Straw that broke the camel's back",
               "Strike a chord",
               "Stroll down memory lane",
               "Strong as an ox",
               "Sunday driver",
               "Swansong",
               "Swear like a sailor",
               "Sweating blood",
               "Sweep me off my feet",
               "Sweet tooth",
               "Swim with the fishes",
               "Swimmingly",

               // T: 64
               "Tables have turned",
               "Take a hike",
               "Take a nosedive",
               "Take a raincheck",
               "Take for granted",
               "Take no prisoners",
               "Taking you down a peg",
               "Taking you for a ride",
               "Take you under my wing",
               "Take stock",
               "Take the bull by its horns",
               "Take the fall",
               "Take the fifth",
               "Take my breath away",
               "Talk is cheap",
               "Talk of the town",
               "Tall drink of water",
               "Tall order",
               "Tall story",
               "Tar baby",
               "Taste of your own medicine",
               "Teacher's pet",
               "Tempt providence",
               "Test the waters",
               "That is the way the cookie crumbles",
               "That makes two of us",
               "That ship has sailed",
               "That's all she wrote",
               "The apple does not fall far from the tree",
               "The be all and end all",
               "The cat's meow",
               "The more the merrier",
               "The plot thickens",
               "The sands of time",
               "Thick as thieves",
               "Thin as a rake",
               "Thin line",
               "Think outside the box",
               "Third degree",
               "Third time's the charm",
               "Thorn in your side",
               "Thrilled to bits",
               "Through thick and thin",
               "Throw down the gauntlet",
               "Throw in the towel",
               "Throw me a bone",
               "Throw the book at you",
               "Tickle your fancy",
               "Tickled pink",
               "Tie the knot",
               "Time is on my side",
               "Tip of the iceberg",
               "Tit for tat",
               "Tongue in cheek",
               "Tough cookie",
               "Tough nut to crack",
               "Treading water",
               "Treasure trove",
               "True colors",
               "Tug at the heartstrings",
               "Turn a blind eye",
               "Turn water into wine",
               "Twinkling of an eye",
               "Two-faced",

               // U: 2
               "Ugly duckling",
               "Under the weather",

               // V: 3
               "Vale of tears",
               "Vicious circle",
               "Virgin territory",

               // W: 10
               "Wag the dog",
               "Wake up and smell the coffee",
               "Walk a mile in my shoes",
               "Walk the plank",
               "Wallflower",
               "War of words",
               "Watching paint dry",
               "Wet blanket",
               "Winners never quit",
               "Woe is me",

               // X: 1
               "X marks the spot",

               // Y: 7
               "Yank my chain",
               "Yes-man",
               "You are what you eat",      
               "You can't make an omelette without breaking eggs",
               "You scratch my back and I'll scratch yours",
               "You're toast",
               "Your name is mud",

               // Z: 3
               "Zero hour",
               "Zig before you zag",
               "Zip your lip",
               
               #endregion
          };

          #endregion

          public static List<string> UserSentences = new List<string>(100);
     }

     /// <summary>
     /// An abstract class which stores a static database of
     /// letters of the alphabet; the player will be able to type these.
     /// </summary>
     public abstract class LetterDatabase
     {
          public static string[] Alphabet = new string[]
          {
               "A", "B", "C", "D", "E", "F", "G", "H", 
               "I", "J", "K", "L", "M", "N", "O", "P",
               "Q", "R", "S", "T", "U", "V", "W", "X", 
               "Y", "Z"
          };
     }

     /// <summary>
     /// Defines a word which can be typed in by the player.
     /// </summary>
     public class TypingWord
     {
          #region Enums

          public enum WordThemeType
          {
               Default,
               Taunt,
               Joke,
               Threat
          };

          public enum WordPersonalityType
          {
               Universal,
               Videogame,
               Music,
          };

          #endregion

          #region Fields

          private string text;
          private WordThemeType theme;
          private List<Keys> keyList;

          // For the "Shot Word" effect.
          private List<char> shotLetters = new List<char>();
          private List<Vector2> shotLettersPositions = new List<Vector2>();
          private List<float> shotLettersRotation = new List<float>();

          private int characterCount;
          private int wordCount;

          #endregion

          #region Properties

          /// <summary>
          /// A String representing the TypingWord.
          /// Setting the value of Text updates the value of KeyList automatically.
          /// </summary>
          public string Text
          {
               get { return text; }
               set
               {
                    text = value;
                    keyList = GetKeys(text);
               }
          }

          /// <summary>
          /// Enum representing the "Theme" of TypingWord's Text.
          /// </summary>
          public WordThemeType Theme
          {
               get { return theme; }
               set { theme = value; }
          }

          /// <summary>
          /// A List of Keys (used to figure out keyboard input).
          /// </summary>
          public List<Keys> KeyList
          {
               get { return keyList; }
          }

          /// <summary>
          /// The length of TypingWord's Text string.
          /// </summary>
          public int Length
          {
               get { return text.Length; }
          }

          /// <summary>
          /// The number of characters in the unaltered Text string.
          /// </summary>
          public int CharacterCount
          {
               get { return characterCount; }
               set { characterCount = value; }
          }

          /// <summary>
          /// The number of words in the unaltered Text string.
          /// 
          /// Simply counts the number of spaces and adds + 1.
          /// </summary>
          public int WordCount
          {
               get { return wordCount; }
               set { wordCount = value; }
          }

          #endregion

          #region Initialization

          /// <summary>
          /// Constructs a new TypingWord with a default text.
          /// </summary>
          public TypingWord()
          {
               text = "Default";
               theme = WordThemeType.Default;
               keyList = GetKeys(text);
          }

          /// <summary>
          /// Constructs a new TypingWord with the specified string.
          /// </summary>
          /// <param name="word">The string the TypingWord represents.</param>
          public TypingWord(string word)
          {
               text = word;
               theme = WordThemeType.Default;
               keyList = GetKeys(text);

               characterCount = text.Length;

               foreach (char c in text)
               {
                    if (c.Equals(" "))
                    {
                         wordCount++;
                    }
               }
          }

          #endregion

          #region Private Generate Word's Corresponding Key List

          /// <summary>
          /// Returns a List of Keys for the specified string.
          /// </summary>
          /// <param name="word">The string to retrieve the Keys for.</param>
          private List<Keys> GetKeys(string word)
          {
               List<Keys> myKeys = TextManager.ConvertToKey(word);

               return myKeys;
          }

          #endregion
     }
}